# Generated by Django 5.2.17 on 2026-10-02 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0013_alter_qualityrequirement_target_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitysettings',
            name='rules_version',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='QualityRulesGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_rules_version', models.PositiveBigIntegerField()),
                ('inherit', models.BooleanField(default=False)),
                ('source_rules_version', models.PositiveBigIntegerField()),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('scope_settings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules_generations', to='quality_control.qualitysettings')),
                ('source_settings', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_rules_generations', to='quality_control.qualitysettings')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope_settings', 'own_rules_version', 'inherit', 'source_settings', 'source_rules_version'), name='quality_rules_generation_unique_descriptor')],
            },
        ),
    ]
