# Generated by Django 5.2.17 on 2026-10-02 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0107_remove_annotationguide_is_public"),
        ("quality_control", "0014_quality_rules_generation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="qualityreport",
            name="generation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reports",
                to="quality_control.qualityrulesgeneration",
            ),
        ),
        migrations.AddField(
            model_name="qualityreport",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("current", "Current"), ("superseded", "Superseded")],
                db_index=True,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "current")),
                fields=("task",),
                name="quality_report_current_task_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "current")),
                fields=("job",),
                name="quality_report_current_job_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "current")),
                fields=("project",),
                name="quality_report_current_project_unique",
            ),
        ),
    ]
